package com.example.demo.model;

import java.util.Date;
import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customers")
public class Customer{

	@DynamoDBHashKey
    @DynamoDBAttribute
    private String customerId;

	@DynamoDBRangeKey
    @DynamoDBAttribute
    private Long valueStampTime = new Date().getTime();

    
    @DynamoDBAttribute
    private String activityType;
    
    @DynamoDBAttribute
    private Double amount;
    
    @DynamoDBAttribute
    private String movement;
}